require 'Items/Distributions'
require "Items/ProceduralDistributions" 
require "Vehicles/VehicleDistributions"

table.insert(SuburbsDistributions.all.postbox.items, "filcher.SFMechanicMag4")
table.insert(SuburbsDistributions.all.postbox.items, 0.2)
table.insert(SuburbsDistributions.all.sidetable.items, "filcher.SFMechanicMag4")
table.insert(SuburbsDistributions.all.sidetable.items, 0.7)

table.insert(ProceduralDistributions.list.BookstoreBooks.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.BookstoreBooks.items, 2)
table.insert(ProceduralDistributions.list.CrateMagazines.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.CrateMagazines.items, 1)
table.insert(ProceduralDistributions.list.CrateMechanics.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.CrateMechanics.items, 1)
table.insert(ProceduralDistributions.list.LibraryBooks.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.LibraryBooks.items, 1)
table.insert(ProceduralDistributions.list.LivingRoomShelf.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.LivingRoomShelf.items, 0.1)
table.insert(ProceduralDistributions.list.LivingRoomShelfNoTapes.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.LivingRoomShelfNoTapes.items, 0.1)
table.insert(ProceduralDistributions.list.MagazineRackMixed.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.MagazineRackMixed.items, 0.5)
table.insert(ProceduralDistributions.list.MechanicShelfBooks.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.MechanicShelfBooks.items, 2)
table.insert(ProceduralDistributions.list.PostOfficeMagazines.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.PostOfficeMagazines.items, 1)
table.insert(ProceduralDistributions.list.ShelfGeneric.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.ShelfGeneric.items, 0.1)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, 1)
table.insert(ProceduralDistributions.list.ToolStoreBooks.items, "filcher.SFMechanicMag4")
table.insert(ProceduralDistributions.list.ToolStoreBooks.items, 2)

table.insert(VehicleDistributions.NormalSports.GloveBox.items, "filcher.SFMechanicMag4")
table.insert(VehicleDistributions.NormalSports.GloveBox.items, 0.2)