require "Items/ProceduralDistributions" 

table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.CycleBattery")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 2)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.NormalCycleSuspension")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 0.5)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.OldCycleBrake")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 3)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.OldCycleMuffler")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 4)

table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.NormalCycleBrake")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 3)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.ModernCycleBrake")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 2)

table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.NormalCycleMuffler")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 3)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.ModernCycleMuffler")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 2)

table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.ModernCycleSuspension")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 2)

table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.NormalCycleTire")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 3)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "filcher.ModernCycleTire")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 2)


table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "NormalATVTire")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 3)
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, "ModernATVTire")
table.insert(ProceduralDistributions.list.WardrobeRedneck.items, 2)